### ISSUE TITLE
Overlay Class making content un clickable 

### ISSUE THREAD

**Issue by omarnazih** [omarnazih/Easy-Bank-LandingPage#1]
[Here](https://github.com/omarnazih/Easy-Bank-LandingPage/blob/main/app/sass/_global.scss) in overlay styling i try display none , visibility hidden it solve the problem but create another.
```css
// Overlay effect
.overlay {
  opacity: 0;
  position: fixed;
  top: 3.6375rem;
  right: 0;
  left: 0;
  bottom: 0;
  background-image: linear-gradient($Dark-Blue, transparent);
}
```

**Comment by omarnazih** [comment]
The problem was in key frames i didn't put the visibility end state 
```css
@keyframes fade-in {
  from{
    // ******Cannot animate Display 
    // after searching *******
    visibility: hidden;
    opacity: 0;
  }
  1%{
    visibility: visible;
    opacity: 0;
  }
  to{
    visibility: visible;  /*Here is the solution */
    opacity: 1;
  }
}
```
